### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by toozande** [sky24h/Face_Animation_Real_Time#1]
hi
I got this error when run camera_local.py
    faceanimation = FaceAnimationClass(source_image_path=args.source_image, use_sr=restore_face)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\myproject\Face_Animation_Real_Time-main\demo_utils.py", line 228, in __init__
    download(id=file_id, output=checkpoint_path, quiet=False)
    ^^^^^^^^
NameError: name 'download' is not defined

**Comment by sky24h** [comment]
Sorry for the bug.
I just updated it, and it should work now.
