### ISSUE TITLE
torch complile, result video dual

### ISSUE THREAD

**Issue by alast0r** [sky24h/Face_Animation_Real_Time#2]
got an error
`AssertionError: Torch not compiled with CUDA enabled`

to fix it change requirements.txt

```
--extra-index-url https://download.pytorch.org/whl/cu118
torch==2.0.1+cu118
```

 it works now, but how can i only get the result as output without the driving input?

**Comment by sky24h** [comment]
> how can i only get the result as output without the driving input?

I'm sorry, I didn't understand. 
Did you mean saving the output as a file with camera input or getting the output without any input?

**Comment by alast0r** [comment]
the driver video in the demo it is trump is always in the output sidebyside with the image getting animated

**Comment by sky24h** [comment]
> the driver video in the demo it is trump is always in the output sidebyside with the image getting animated

You can replace the input driving video by replacing the './assets/driving.mp4'(the path of trump video) with the path of your custom video at [here](https://github.com/sky24h/Face_Animation_Real_Time#2-for-input-driving-video)
Btw, you can replace the path of source_image as well.
