### ISSUE TITLE
How to use the webcam mode?

### ISSUE THREAD

**Issue by hacksider** [sky24h/Face_Animation_Real_Time#3]
Ok, so I just started the application. I tried using the webcam mode and running it through the console and it runs. It opens my camera and shows fps (17 fps). But I don't know how to preview what is being captured. It just opened the camera and shows fps but I cant see anything aside from that.

**Comment by sky24h** [comment]
Hi, @hacksider. Appreciate your report!
It appears I overlooked including the preview code. 
I've just made the update, and now a window should pop up. 
Feel free to adjust the window size as needed. Thanks!

**Comment by hacksider** [comment]
Awesome! Everything looks fine now! Thanks a lot!
